### ISSUE TITLE
Decide on docblock standard and backport codebase

### ISSUE THREAD

**Issue by lucaswoj** [manifold-lang/manifold#50]
Should we have docblocks and what standards should we adhere to?

In particular, I don't care for the `@author` attribute because it always falls out of date and `git blame` does a much better job of conveying the nuanced history of each line of source.

I would be ok with saying no docblocks and just comment as needed.

**Comment by maxqchen** [comment]
I think we should have them for any non trivial functions. Things like getters and such probably don't need them.

**Comment by lucaswoj** [comment]
I agree -- I'm saying that in leu of adhering to the docblock spec, we should just comment as necessary (such as for complicated methods). That being said, I've never worked in a codebase that made heavy use of docblocks and can't really speak to their benefits.

**Comment by maxqchen** [comment]
By the standard do you mean having @param, @return and such for each block? If so we probably don't need to enforce that. But a block on, say, the TypeMismatchException that said it also accepted Values as actual because the input parameters are the result of expressions that may not even evaluate to a type would have helped with my confusion and the edit that came from it :)

**Comment by lucaswoj** [comment]
I agree that that class could've used more comments.

So, lets agree to ignore the docblock standard and encourage commenting, especially on complex methods.
