### ISSUE TITLE
Retain the result of an Expression evaluation

### ISSUE THREAD

**Issue by maxqchen** [manifold-lang/manifold#53]
Given that a call to an Expression's method may result in a computation of arbitrary complexity (eg. Expression -> Expression ( Expression ) for function calls), I was thinking that it would be advantageous of us to retain the results of all Expression calls so that this computation is only evaluated once.

This could be done with something like this:

``` java
private TypeValue type = null;

public TypeValue getType() {
  if(t == null) {
    t = cGetType();
  }
  return t;
}

protected abstract TypeValue cGetType(); // overwritten by children
```

Given how protected works in java, this may seem a bit awkward since both will be exposed, so we may need to throw it in its own package or do some other method to hide the protected methods.

I can't think of any cases where an Expression will end up returning different results between calls (ie. it suddenly returns a different type or is no longer compiletime evaluable) so I think this should work fine and save us some redundant calls.

edit: I suppose this is kind of similar to what we want during the tree compression stage?

**Comment by lucaswoj** [comment]
I've thought a bit about this. I'm inclined to avoid this because
- every expression need only be evaluated exactly once in our compiletime environment as we compress the tree
- executing some expressions has side effects

There may be one-off situations where memorization would increase peformance but lets cross that bridge when we get there :smile:
