### ISSUE TITLE
Write an intermediate JSON seralizer/deserializer

### ISSUE THREAD

**Issue by maxqchen** [manifold-lang/manifold#86]
I don't see where I can assign this to myself / add the labels?

**Comment by lucaswoj** [comment]
Thanks for opening this Max! I'll show you how to manage labels during the team meeting tomorrow. I'm sure you can find [some information on google, though](http://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github)! 

Also, you should write the issue title as a verb phrase. "Write an intermediate parser..." instead of "Intermediate parser..."

**Comment by maxqchen** [comment]
Here's my thoughts on implementing the writing portion, let me know if it seems sane before I go ahead with it:

Pick up the org.json package from maven as a dependency.
Add an abstract method to the top level classes TypeDefinition and Value, signature of 

```
JSONObject serialize(); // or some alternative naming?
```

Each sub-class's implementation of this method will build a JSON object, populate it with its own information and recursively populate it with any other Type/Value objects it contains.

**Comment by lucaswoj** [comment]
Sounds like a perfect v1! 

(Approved at 20,000 ft somewhere over California)
—

**Comment by maxqchen** [comment]
Do we want to keep this open since the commit was only a partial solution?

**Comment by lucaswoj** [comment]
Yes, frankly, I'd like to see more thought put into compliance with our intermediate spec. The default output is not as clean as it could be.
